### ISSUE TITLE
code diff layout error when pr info fixed

### ISSUE THREAD

**Issue by hhshii** [StylishThemes/GitHub-FixedHeader#14]
in PR files changed page,code diff layout may display error when the PR title fixed

* **Browser**:Chrome 
* **Operating System**:Macos
* **Link to page with the issue**:https://github.com/StylishThemes/GitHub-FixedHeader/pull/13/files
* **Screenshot**:
![image](https://user-images.githubusercontent.com/14303098/54031559-0c897b00-41ea-11e9-9dc2-898a30a83e03.png)

**Comment by Mottie** [comment]
Hi @GFwer!

Thanks for reporting this problem. It should be fixed in the latest release. Please test it and let us know!

**Comment by hhshii** [comment]
@Mottie thanks! now it's working good!

**Comment by Ash258** [comment]
I am experiencing this again on Chrome **73.0.3683.86 (Official Build) (64-bit)** and **Windows 10 1809 17763.376** with fixed header **1.2.12**

https://github.com/Microsoft/vscode/pull/71301/files

# Enabled style

![image](https://user-images.githubusercontent.com/13260377/55147853-74771580-5147-11e9-957b-9380f12a35eb.png)

# After disabling

![image](https://user-images.githubusercontent.com/13260377/55147909-8e185d00-5147-11e9-9690-5ab45f920f8c.png)

**Comment by Mottie** [comment]
Hi @Ash258!

Make sure the style is up-to-date. Worse case scenario, remove and reinstall it.

**Comment by Ash258** [comment]
Style version is 1.2.12, which is same as in readme file. I will try to uninstall and install again.

Edit:
Still same. First file of PR is always shifted.

**Comment by Mottie** [comment]
Hmm, I'm using the same versions (didn't check Windows), and it's not behaving that way for me.

The way I had to fix it before was to use `overflow-x: unset` ([ref](https://github.com/StylishThemes/GitHub-FixedHeader/commit/2fddd061f9cfc4a2b4170e05928a535cdfcc9156#diff-0)) which is really super weird. I have yet to report the issue/search for the issue in webkit because I think it's a browser bug.

**Comment by xt0rted** [comment]
I can repro this in chrome on windows.

![2019-03-28_17-49-02](https://user-images.githubusercontent.com/831974/55195083-d6ed0780-5181-11e9-949f-4285a1531acb.gif)

This css looks to resolve it.

```css
.diff-view .file .highlight {
  width: 100%;
}
```

**Comment by xt0rted** [comment]
@Mottie the change in 2fddd061f9cfc4a2b4170e05928a535cdfcc9156 was reverted in bd3ae5a1db75aced0a0c9e7b34d68f224149182b which is why this came back up. But the css above looks to resolve it for me.

This page might also be acting weird because sticky file headers is now built-in (#16) and we might need to adjust the css to accommodate their recent changes.

**Comment by Mottie** [comment]
Weird, it still isn't jumping over for me. I'm not sure why.

**Comment by xt0rted** [comment]
I'm seeing it in Chrome 73 & FF 66 on macOS, and Chrome 73 & FF 67 on Windows.
