### ISSUE TITLE
Code blocks are not limited to box

### ISSUE THREAD

**Issue by Ash258** [StylishThemes/GitHub-FixedHeader#17]
* **Browser**: Chrome  73.0.3683.75 
* **Operating System**: Windows 10 1809 17763.379
* **Link to page with the issue**: https://github.com/Microsoft/vscode/commit/10c0126e4b69d3c0672cdb10cd8f0c987304ac4b
* **Screenshot**:

![Code block](https://i.imgur.com/oET4fjC.gif)

**Comment by the-j0k3r** [comment]
Hello and thank you for your report.

I wonder if this is actually related to https://github.com/StylishThemes/GitHub-Dark/commit/09ca5032e6bac947b4ceb614a9c5cae8f608d36c#comments rather than anything in this Style.

**Comment by Ash258** [comment]
Github dark style was disabled and page reloaded so I don't think it could cause this.

**Comment by Podesta** [comment]
I believe it started yesterday. At least that's when I noticed it. Github seems to have changed their design a bit more. I haven't bothered to look what exactly changed yet, but at least for me the fixed header style is currently broken.

**Comment by xt0rted** [comment]
The overflow is coming from this rule, when I turn it off the issue goes away.

https://github.com/StylishThemes/GitHub-FixedHeader/blob/53dc3485a8b25bf9451b12ad093bb9ab9197c457/github-fixed-header.user.css#L67-L70

GitHub is setting the overflow of these elements to `auto` with an inline style so the custom one either needs to be updated or removed. This is more than likely a result of the file header change from 2 days ago (#16).

The page header is also being offset by about 60px due to the newly renamed `.Header-old` class.

**Comment by Mottie** [comment]
I didn't notice this at first because I have the [Code wrap toggle](https://greasyfork.org/en/scripts/18789-github-toggle-code-wrap) userscript installed. It's been fixed in the latest update! Thanks for reporting the problem.
