### ISSUE TITLE
Doesn't play nice with OctoTree

### ISSUE THREAD

**Issue by snowe2010** [StylishThemes/GitHub-FixedHeader#6]
OctoTree overruns the header if expanded with Fixed-Header

**Comment by Mottie** [comment]
Hi @snowe2010!

Hmm, yeah that will be a difficult fix with pure CSS since Octotree allows for adjusting the width of the left panel. I can override the set margin-left, but if the panel is really wide, then it will still overlap some elements in the header.

This won't be a perfect fix, but it should make things a little bit easier.

**Comment by snowe2010** [comment]
Fantastic! Thank you so much!

**Comment by snowe2010** [comment]
Ah you know what. I wasn't being clear at all in what I was talking about. I completely forgot that I use Github Wide which makes Github spread all the way to the edge. I get a situation where if the octotree panel is at its very smallest it still overruns the header because the header expands all the way to the left. :/

**Comment by DaniloNovakovic** [comment]
@Mottie  I feel that **this workaround should be noted somewhere in the README.** Reducing the width of Octotree solves the problem and I consider it as a good-enough solution (at least for my own needs), but I still had to come here and figure it out as reducing the width of Octotree's side panel width didn't really even cross my mind.
